name: Lint

on:
  workflow_call: { }
  push:
    branches:
      - main

jobs:
  lint_proto:
    name: Lint Proto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: api
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: api
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1'

  lint_go:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
